options:
  logging: CLOUD_LOGGING_ONLY

steps:

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'africa-south1-docker.pkg.dev/thermal-diorama-443207-k0/infra-task/frontend:${SHORT_SHA}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'africa-south1-docker.pkg.dev/thermal-diorama-443207-k0/infra-task/frontend:${SHORT_SHA}']

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'frontend', 
           '--image=africa-south1-docker.pkg.dev/thermal-diorama-443207-k0/infra-task/frontend:${SHORT_SHA}', 
           '--region', 'africa-south1', '--platform', 'managed', 
           '--allow-unauthenticated']


images:
  - africa-south1-docker.pkg.dev/thermal-diorama-443207-k0/infra-task/frontend:${SHORT_SHA}
